"""Lyzr Automata framework adapter for AgentIR."""

from pathlib import Path

import yaml

from agentir.adapters.base import FrameworkAdapter
from agentir.capabilities.matrix import FRAMEWORK_CAPABILITY_MATRICES
from agentir.capabilities.status import CapabilitySupport
from agentir.domain.agent import AgentSpec
from agentir.domain.exceptions import AdapterError
from agentir.domain.instructions import InstructionsSpec
from agentir.domain.manifest import AgentIRManifest
from agentir.domain.model import ModelSpec
from agentir.domain.node import NodeSpec
from agentir.domain.provenance import SourceProvenance
from agentir.domain.tool import ToolInputSchema, ToolSpec
from agentir.domain.workflow import WorkflowSpec


class LyzrAdapter(FrameworkAdapter):
    """Adapter for Lyzr Automata pipelines and task agents."""

    framework_name: str = "lyzr"
    framework_version_range: str = ">=0.1.20,<1.0.0"
    adapter_version: str = "0.1.0"

    def get_capabilities(self) -> dict[str, CapabilitySupport]:
        return FRAMEWORK_CAPABILITY_MATRICES["lyzr"]

    def can_import(self, source: Path | str) -> bool:
        path = Path(source)
        if not path.is_file():
            return False
        content = path.read_text(encoding="utf-8")
        if path.suffix in (".yaml", ".yml", ".json") and "framework" in content:
            try:
                data = yaml.safe_load(content)
                return isinstance(data, dict) and data.get("framework") == "lyzr"
            except Exception:
                return False
        return "lyzr_automata" in content or "LinearSyncPipeline" in content

    def import_manifest(self, source: Path | str) -> AgentIRManifest:
        path = Path(source).resolve()
        if not path.is_file():
            raise AdapterError(f"Lyzr source file not found: {path}")

        content = path.read_text(encoding="utf-8")
        data = yaml.safe_load(content) if path.suffix in (".yaml", ".yml", ".json") else {}

        if not data:
            # Simple fallback for text / source parsing
            data = {
                "name": path.stem,
                "role": "Lyzr Worker",
                "prompt_persona": "You are an automated task agent.",
            }

        tools: list[ToolSpec] = []
        for t_data in data.get("tools", []):
            tools.append(
                ToolSpec(
                    id=t_data.get("name", "tool"),
                    name=t_data.get("name", "tool"),
                    description=t_data.get("description", ""),
                    input_schema=ToolInputSchema(),
                )
            )

        agent = AgentSpec(
            id=data.get("id", "lyzr_agent"),
            name=data.get("name", "Lyzr Agent"),
            model=ModelSpec(provider="openai", model_id=data.get("model", "gpt-4o")),
            instructions=InstructionsSpec(
                system_prompt=data.get("prompt_persona", "You are an automated task agent."),
                role=data.get("role", "Worker"),
            ),
            tools=tuple(tools),
            provenance=SourceProvenance(
                source_framework="lyzr",
                source_identifier=path.name,
                source_file=str(path),
            ),
        )

        nodes = (
            NodeSpec(id="task_1", type="agent", name="Execute Task", agent_id=agent.id),
        )
        wf = WorkflowSpec(
            id=f"{path.stem}_pipeline",
            name=f"Lyzr Pipeline {path.stem}",
            entry_node_id="task_1",
            finish_node_ids=("END",),
            nodes=nodes,
            provenance=SourceProvenance(
                source_framework="lyzr",
                source_identifier=path.name,
                source_file=str(path),
            ),
        )

        return AgentIRManifest(
            name=path.stem,
            agents=(agent,),
            workflows=(wf,),
            provenance=SourceProvenance(
                source_framework="lyzr",
                source_identifier=path.name,
                source_file=str(path),
            ),
        )

    def export_manifest(
        self, manifest: AgentIRManifest, target_directory: Path | str
    ) -> list[Path]:
        out_dir = Path(target_directory).resolve()
        out_dir.mkdir(parents=True, exist_ok=True)
        generated_files: list[Path] = []

        code_lines: list[str] = [
            "# Auto-generated by AgentIR (https://github.com/agentir/agentir)",
            "# Target: Lyzr Automata",
            "# Target version range: >=0.1.20,<1.0.0",
            "",
            "import os",
            "from lyzr_automata.ai_models.openai import OpenAIModel",
            "from lyzr_automata import Agent, Task",
            "from lyzr_automata.pipelines.linear_sync_pipeline import LinearSyncPipeline",
            "",
            "open_ai_model = OpenAIModel(",
            '    api_key=os.environ.get("OPENAI_API_KEY", ""),',
            '    parameters={"model": "gpt-4o", "temperature": 0.7},',
            ")",
            "",
        ]

        task_vars: list[str] = []
        for idx, agent in enumerate(manifest.agents):
            agent_var = f"agent_{idx}"
            task_var = f"task_{idx}"
            task_vars.append(task_var)

            persona = agent.instructions.system_prompt.replace('"', '\\"')
            code_lines.extend(
                [
                    f"{agent_var} = Agent(",
                    f'    role="{agent.instructions.role or agent.name}",',
                    f'    prompt_persona="""{persona}""",',
                    ")",
                    "",
                    f"{task_var} = Task(",
                    f'    name="Task for {agent.name}",',
                    '    output_type="text",',
                    '    input_type="text",',
                    "    model=open_ai_model,",
                    f"    agent={agent_var},",
                    '    log_output=True,',
                    '    instructions="Complete the requested assignment.",',
                    ")",
                    "",
                ]
            )

        tasks_repr = f"[{', '.join(task_vars)}]" if task_vars else "[]"
        code_lines.extend(
            [
                "pipeline = LinearSyncPipeline(",
                f'    name="{manifest.name} Pipeline",',
                "    completion_message='Pipeline completed successfully.',",
                f"    tasks={tasks_repr},",
                ")",
                "",
                'if __name__ == "__main__":',
                '    output = pipeline.run(input_dict={"input": "Hello from AgentIR"})',
                "    print(output)",
            ]
        )

        agent_py = out_dir / "agent.py"
        agent_py.write_text("\n".join(code_lines) + "\n", encoding="utf-8")
        generated_files.append(agent_py)

        reqs = out_dir / "requirements.txt"
        reqs.write_text("lyzr-automata>=0.1.20\n", encoding="utf-8")
        generated_files.append(reqs)

        return generated_files
