"""Capability support matrices for supported agent frameworks."""

from agentir.capabilities.status import CapabilitySupport, SemanticLossRisk, SupportLevel


def _native(cap_id: str, desc: str = "") -> CapabilitySupport:
    """Helper to declare a native capability with zero semantic loss risk."""
    return CapabilitySupport(
        capability_id=cap_id,
        support_level=SupportLevel.NATIVE,
        semantic_loss_risk=SemanticLossRisk.NONE,
        description=desc,
    )


FRAMEWORK_CAPABILITY_MATRICES: dict[str, dict[str, CapabilitySupport]] = {
    "langgraph": {
        "model_calling": _native("model_calling"),
        "tool_calling": _native("tool_calling"),
        "structured_output": _native("structured_output"),
        "streaming": _native("streaming"),
        "memory": CapabilitySupport(
            "memory",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Mapped to LangGraph messages channel with add_messages reducer.",
            required_adapter_shim="langgraph.channels.MessagesChannel",
        ),
        "persistent_state": _native("persistent_state"),
        "checkpointing": _native("checkpointing"),
        "handoff": CapabilitySupport(
            "handoff",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Mapped to conditional edges routing to target agent nodes.",
            required_adapter_shim="conditional_edge_router",
        ),
        "routing": _native("routing"),
        "conditional_edges": _native("conditional_edges"),
        "parallel_execution": _native("parallel_execution"),
        "human_approval": _native("human_approval"),
        "interrupts": _native(
            "interrupts",
            desc="Native interrupt_before / interrupt_after execution pausing.",
        ),
        "retries": _native("retries"),
        "timeout": _native("timeout"),
        "cancellation": _native("cancellation"),
        "lifecycle_hooks": _native("lifecycle_hooks"),
        "middleware": _native("middleware"),
        "tracing": _native("tracing"),
        "guardrails": CapabilitySupport(
            "guardrails",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Emitted as pre-flight validation node before agent node.",
        ),
        "sandboxing": CapabilitySupport(
            "sandboxing",
            SupportLevel.EMULATED,
            SemanticLossRisk.MEDIUM,
            emulation_strategy="External process/container isolation required.",
        ),
        "multi_agent": _native("multi_agent"),
        "async_execution": _native("async_execution"),
    },
    "agno": {
        "model_calling": _native("model_calling"),
        "tool_calling": _native("tool_calling"),
        "structured_output": _native("structured_output"),
        "streaming": _native("streaming"),
        "memory": _native("memory"),
        "persistent_state": _native("persistent_state"),
        "checkpointing": CapabilitySupport(
            "checkpointing",
            SupportLevel.UNSUPPORTED,
            SemanticLossRisk.HIGH,
            description="Agno does not offer superstep graph time-travel checkpointing.",
        ),
        "handoff": CapabilitySupport(
            "handoff",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Mapped to Agno team leader delegation and tool transfers.",
            required_adapter_shim="agno.team.delegate",
        ),
        "routing": _native("routing"),
        "conditional_edges": CapabilitySupport(
            "conditional_edges",
            SupportLevel.EMULATED,
            SemanticLossRisk.MEDIUM,
            emulation_strategy="Compiled into procedural Python branching inside an Agno Workflow.",
        ),
        "parallel_execution": CapabilitySupport(
            "parallel_execution",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Async multi-agent concurrent dispatch.",
        ),
        "human_approval": CapabilitySupport(
            "human_approval",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Interactive confirmation hook in tool execution.",
        ),
        "interrupts": CapabilitySupport(
            "interrupts",
            SupportLevel.EMULATED,
            SemanticLossRisk.HIGH,
            emulation_strategy="Simulated via workflow step pauses requiring session resume.",
        ),
        "retries": _native("retries"),
        "timeout": _native("timeout"),
        "cancellation": _native("cancellation"),
        "lifecycle_hooks": _native("lifecycle_hooks"),
        "middleware": _native("middleware"),
        "tracing": _native("tracing"),
        "guardrails": CapabilitySupport(
            "guardrails",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Pre-run and post-run validation hooks.",
        ),
        "sandboxing": CapabilitySupport(
            "sandboxing",
            SupportLevel.UNSUPPORTED,
            SemanticLossRisk.HIGH,
            description="Native sandboxing not supported in Agno core.",
        ),
        "multi_agent": _native("multi_agent"),
        "async_execution": _native("async_execution"),
    },
    "openai_agents": {
        "model_calling": _native("model_calling"),
        "tool_calling": _native("tool_calling"),
        "structured_output": _native("structured_output"),
        "streaming": _native("streaming"),
        "memory": CapabilitySupport(
            "memory",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Mapped to OpenAI thread context message history.",
        ),
        "persistent_state": CapabilitySupport(
            "persistent_state",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Context variables passed in Runner.run.",
        ),
        "checkpointing": CapabilitySupport(
            "checkpointing",
            SupportLevel.UNSUPPORTED,
            SemanticLossRisk.HIGH,
            description="OpenAI Agents SDK does not support graph superstep state checkpointing.",
        ),
        "handoff": _native("handoff"),
        "routing": _native("routing"),
        "conditional_edges": CapabilitySupport(
            "conditional_edges",
            SupportLevel.UNSUPPORTED,
            SemanticLossRisk.CRITICAL,
            description="OpenAI Agents SDK is agent-handoff based, not a general graph engine.",
        ),
        "parallel_execution": CapabilitySupport(
            "parallel_execution",
            SupportLevel.UNSUPPORTED,
            SemanticLossRisk.HIGH,
            description="Parallel branch execution not supported in core SDK.",
        ),
        "human_approval": CapabilitySupport(
            "human_approval",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Handled via guardrail intercept or client loop pause.",
        ),
        "interrupts": CapabilitySupport(
            "interrupts",
            SupportLevel.UNSUPPORTED,
            SemanticLossRisk.HIGH,
            description="No graph node interrupts in OpenAI Agents SDK.",
        ),
        "retries": CapabilitySupport(
            "retries",
            SupportLevel.EMULATED,
            SemanticLossRisk.LOW,
            emulation_strategy="Emulated via external runner retry loop.",
        ),
        "timeout": CapabilitySupport(
            "timeout",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Handled via runner execution timeout.",
        ),
        "cancellation": _native("cancellation"),
        "lifecycle_hooks": _native("lifecycle_hooks"),
        "middleware": CapabilitySupport(
            "middleware",
            SupportLevel.UNSUPPORTED,
            SemanticLossRisk.MEDIUM,
        ),
        "tracing": _native("tracing"),
        "guardrails": _native("guardrails"),
        "sandboxing": CapabilitySupport(
            "sandboxing",
            SupportLevel.UNSUPPORTED,
            SemanticLossRisk.HIGH,
        ),
        "multi_agent": _native("multi_agent"),
        "async_execution": _native("async_execution"),
    },
    "lyzr": {
        "model_calling": _native("model_calling"),
        "tool_calling": _native("tool_calling"),
        "structured_output": _native("structured_output"),
        "streaming": _native("streaming"),
        "memory": CapabilitySupport(
            "memory",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Mapped to Lyzr session message context.",
        ),
        "persistent_state": _native("persistent_state"),
        "checkpointing": CapabilitySupport(
            "checkpointing",
            SupportLevel.UNSUPPORTED,
            SemanticLossRisk.HIGH,
            description="Superstep graph checkpointing not supported.",
        ),
        "handoff": CapabilitySupport(
            "handoff",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Pipeline sequential task handoff.",
        ),
        "routing": _native("routing"),
        "conditional_edges": CapabilitySupport(
            "conditional_edges",
            SupportLevel.EMULATED,
            SemanticLossRisk.HIGH,
            emulation_strategy="Linear pipeline branching with conditional task controllers.",
        ),
        "parallel_execution": _native("parallel_execution"),
        "human_approval": _native("human_approval"),
        "interrupts": CapabilitySupport(
            "interrupts",
            SupportLevel.EMULATED,
            SemanticLossRisk.MEDIUM,
            emulation_strategy="Pipeline task pause for human review.",
        ),
        "retries": _native("retries"),
        "timeout": _native("timeout"),
        "cancellation": _native("cancellation"),
        "lifecycle_hooks": _native("lifecycle_hooks"),
        "middleware": CapabilitySupport(
            "middleware", SupportLevel.UNSUPPORTED, SemanticLossRisk.MEDIUM
        ),
        "tracing": _native("tracing"),
        "guardrails": CapabilitySupport(
            "guardrails",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Input/output validation tasks.",
        ),
        "sandboxing": _native("sandboxing"),
        "multi_agent": _native("multi_agent"),
        "async_execution": _native("async_execution"),
    },
    "mcp": {
        "tool_calling": _native("tool_calling"),
        "structured_output": _native("structured_output"),
        "model_calling": CapabilitySupport(
            "model_calling",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Delegated to client host application.",
        ),
        "sandboxing": _native(
            "sandboxing",
            desc="Isolated via stdio/SSE protocol boundary.",
        ),
        "async_execution": _native("async_execution"),
    },
    "crewai": {
        "model_calling": _native("model_calling"),
        "tool_calling": _native("tool_calling"),
        "structured_output": _native("structured_output"),
        "streaming": _native("streaming"),
        "memory": _native("memory"),
        "persistent_state": CapabilitySupport(
            "persistent_state",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Mapped to CrewAI short_term/long_term storage.",
        ),
        "checkpointing": CapabilitySupport(
            "checkpointing",
            SupportLevel.UNSUPPORTED,
            SemanticLossRisk.HIGH,
            description="Graph superstep checkpointing not supported.",
        ),
        "handoff": _native("handoff", desc="Native agent delegation and task routing."),
        "routing": _native("routing"),
        "conditional_edges": CapabilitySupport(
            "conditional_edges",
            SupportLevel.EMULATED,
            SemanticLossRisk.MEDIUM,
            emulation_strategy="Compiled into CrewAI Flow @router methods.",
        ),
        "parallel_execution": _native("parallel_execution"),
        "human_approval": _native("human_approval"),
        "interrupts": CapabilitySupport(
            "interrupts",
            SupportLevel.EMULATED,
            SemanticLossRisk.MEDIUM,
            emulation_strategy="Task human_input pause.",
        ),
        "retries": _native("retries"),
        "timeout": _native("timeout"),
        "cancellation": _native("cancellation"),
        "lifecycle_hooks": _native("lifecycle_hooks"),
        "middleware": CapabilitySupport(
            "middleware", SupportLevel.UNSUPPORTED, SemanticLossRisk.MEDIUM
        ),
        "tracing": _native("tracing"),
        "guardrails": CapabilitySupport(
            "guardrails",
            SupportLevel.ADAPTER,
            SemanticLossRisk.LOW,
            description="Task validation functions.",
        ),
        "sandboxing": CapabilitySupport(
            "sandboxing",
            SupportLevel.EMULATED,
            SemanticLossRisk.MEDIUM,
        ),
        "multi_agent": _native("multi_agent"),
        "async_execution": _native("async_execution"),
    },
}
