"""AgentIR schema, serialization, and canonicalization layer."""

from agentir.schema.canonical import (
    compute_canonical_hash,
    to_canonical_dict,
    to_canonical_json,
)
from agentir.schema.models import (
    AgentIRManifestSchema,
    AgentSpecSchema,
    EdgeSpecSchema,
    ExecutionPolicySchema,
    GuardSpecSchema,
    HandoffSpecSchema,
    InstructionsSpecSchema,
    MemorySpecSchema,
    ModelSpecSchema,
    NodeSpecSchema,
    OutputSpecSchema,
    SourceProvenanceSchema,
    StateChannelSpecSchema,
    StateSpecSchema,
    ToolInputSchemaModel,
    ToolParameterPropertySchema,
    ToolSpecSchema,
    WorkflowSpecSchema,
)
from agentir.schema.serializer import (
    deserialize_agent_from_dict,
    deserialize_manifest_from_dict,
    deserialize_manifest_from_json,
    deserialize_manifest_from_yaml,
    load_manifest_from_file,
    serialize_agent_to_dict,
    serialize_manifest_to_dict,
    serialize_manifest_to_json,
    serialize_manifest_to_yaml,
)

__all__ = [
    "AgentIRManifestSchema",
    "AgentSpecSchema",
    "EdgeSpecSchema",
    "ExecutionPolicySchema",
    "GuardSpecSchema",
    "HandoffSpecSchema",
    "InstructionsSpecSchema",
    "MemorySpecSchema",
    "ModelSpecSchema",
    "NodeSpecSchema",
    "OutputSpecSchema",
    "SourceProvenanceSchema",
    "StateChannelSpecSchema",
    "StateSpecSchema",
    "ToolInputSchemaModel",
    "ToolParameterPropertySchema",
    "ToolSpecSchema",
    "WorkflowSpecSchema",
    "compute_canonical_hash",
    "deserialize_agent_from_dict",
    "deserialize_manifest_from_dict",
    "deserialize_manifest_from_json",
    "deserialize_manifest_from_yaml",
    "load_manifest_from_file",
    "serialize_agent_to_dict",
    "serialize_manifest_to_dict",
    "serialize_manifest_to_json",
    "serialize_manifest_to_yaml",
    "to_canonical_dict",
    "to_canonical_json",
]
